In [15]:
import numpy as np
import pandas as pd
import calendar
import datetime as dt 
from matplotlib import pyplot as plt

In [2]:
df = pd.read_csv('country_vaccinations.csv')

In [11]:
df.head(10)

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
5,Afghanistan,AFG,2021-02-27,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
6,Afghanistan,AFG,2021-02-28,8200.0,8200.0,NaN,NaN,1367.0,0.02,0.02,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
7,Afghanistan,AFG,2021-03-01,NaN,NaN,NaN,NaN,1580.0,NaN,NaN,NaN,40.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
8,Afghanistan,AFG,2021-03-02,NaN,NaN,NaN,NaN,1794.0,NaN,NaN,NaN,45.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
9,Afghanistan,AFG,2021-03-03,NaN,NaN,NaN,NaN,2008.0,NaN,NaN,NaN,50.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/

## Unique country

In [4]:
df['country'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Anguilla', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia', 'Bonaire Sint Eustatius and Saba',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde',
       'Cayman Islands', 'Central African Republic', 'Chad', 'Chile',
       'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands',
       'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao',
       'Cyprus', 'Czechia', 'Democratic Republic of Congo', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'England', 'Equatorial Guinea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Faeroe Islands', 'Falkland Islands',
       'Fiji', 'Finland', 'France', 'French Polynesia', 'Gabon', 'Gambia',
       'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland',
       'Grenada', 'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau',
       'Guyana', 'Haiti', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland',
       'India', 'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Isle of Man',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jersey', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'Macao',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Mauritania', 'Mauritius', 'Mexico', 'Moldova', 'Monaco',
       'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands',
       'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'Niue', 'North Macedonia', 'Northern Cyprus', 'Northern Ireland',
       'Norway', 'Oman', 'Pakistan', 'Palestine', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn',
       'Poland', 'Portugal', 'Qatar', 'Romania', 'Russia', 'Rwanda',
       'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Scotland', 'Senegal',
       'Serbia', 'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Korea',
       'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
       'Thailand', 'Timor', 'Togo', 'Tokelau', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
       'Wales', 'Wallis and Futuna', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype=object)

## Null Values

In [5]:
df.isnull()

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,False,False,False,False,False,True,True,True,False,False,True,True,False,False,False
1,False,False,False,True,True,True,True,False,True,True,True,False,False,False,False
2,False,False,False,True,True,True,True,False,True,True,True,False,False,False,False
3,False,False,False,True,True,True,True,False,True,True,True,False,False,False,False
4,False,False,False,True,True,True,True,False,True,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86507,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
86508,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
86509,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
86510,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
86511,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

## Average cases in a country

In [17]:
p3 = pd.read_csv('covid.csv')
p3.head()

,Unnamed: 0,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa

In [20]:
p3['Confirmed'].mean()

88130.935828877

In [27]:
P2 = pd.read_csv('covid.csv').fillna(0)
P2.head(100)
del P2['Unnamed: 0']
P2

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,West Bank and Gaza,10621,78,3752,6791,152,2,0,0.73,35.33,2.08,8916,1705,19.12,Eastern Mediterranean
183,Western Sahara,10,1,8,1,0,0,0,10.00,80.00,12.50,10,0,0.00,Africa
184,Yemen,1691,483,833,375,10,4,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean
185,Zambia,4552,140,2815,1597,71,1,465,3.08,61.84,4.97,3326,1226,36.86,Africa
186,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa

## Maximum Confirmed cases

In [28]:
P2['Confirmed'].max()

4290259

## Maximum deaths

In [29]:
P2['Deaths'].max()

148011

## Null Value

In [30]:
P2 = P2.fillna(0)

In [31]:
P2

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,West Bank and Gaza,10621,78,3752,6791,152,2,0,0.73,35.33,2.08,8916,1705,19.12,Eastern Mediterranean
183,Western Sahara,10,1,8,1,0,0,0,10.00,80.00,12.50,10,0,0.00,Africa
184,Yemen,1691,483,833,375,10,4,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean
185,Zambia,4552,140,2815,1597,71,1,465,3.08,61.84,4.97,3326,1226,36.86,Africa
186,Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa

In [32]:
df = pd.read_csv('country_vaccinations.csv')
df

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86507,Zimbabwe,ZWE,2022-03-25,8691642.0,4814582.0,3473523.0,139213.0,69579.0,57.59,31.90,23.02,4610.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
86508,Zimbabwe,ZWE,2022-03-26,8791728.0,4886242.0,3487962.0,100086.0,83429.0,58.25,32.38,23.11,5528.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
86509,Zimbabwe,ZWE,2022-03-27,8845039.0,4918147.0,3493763.0,53311.0,90629.0,58.61,32.59,23.15,6005.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
86510,Zimbabwe,ZWE,2022-03-28,8934360.0,4975433.0,3501493.0,89321.0,100614.0,59.20,32.97,23.20,6667.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...
86511,Zimbabwe,ZWE,2022-03-29,9039729.0,5053114.0,3510256.0,105369.0,103751.0,59.90,33.48,23.26,6874.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...

In [33]:
import datetime as dt 
print(dir(dt))

['MAXYEAR', 'MINYEAR', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'date', 'datetime', 'datetime_CAPI', 'sys', 'time', 'timedelta', 'timezone', 'tzinfo']

## ADD YEAR COLUMN, MONTH COLUMN,AND DAY COLUMN (jan-dec)

In [35]:
df = pd.read_csv('country_wise_latest.csv')
df['date'] = pd.to_datetime(df['date'])

df['year'] = df['date'].dt.year
df['month'] = df['date'].dt.month
df['day'] = df['date'].dt.day
df['month'] = df['month'].astype(int)

df['month'] = df['month'].apply(lambda x : calendar.month_abbr[x])
df.fillna(0)
df.to_csv('country_wise_latest.csv')
df

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,...,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website,year,month,day
0,0,0,0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,...,0.00,0.00,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,2021,Feb,22
1,1,1,1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,2021,Feb,23
2,2,2,2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,2021,Feb,24
3,3,3,3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,2021,Feb,25
4,4,4,4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,2021,Feb,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86507,86507,86507,86507,Zimbabwe,ZWE,2022-03-25,8691642.0,4814582.0,3473523.0,139213.0,...,57.59,31.90,23.02,4610.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,2022,Mar,25
86508,86508,86508,86508,Zimbabwe,ZWE,2022-03-26,8791728.0,4886242.0,3487962.0,100086.0,...,58.25,32.38,23.11,5528.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,2022,Mar,26
86509,86509,86509,86509,Zimbabwe,ZWE,2022-03-27,8845039.0,4918147.0,3493763.0,53311.0,...,58.61,32.59,23.15,6005.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,2022,Mar,27
86510,86510,86510,86510,Zimbabwe,ZWE,2022-03-28,8934360.0,4975433.0,3501493.0,89321.0,...,59.20,32.97,23.20,6667.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,2022,Mar,28
86511,86511,86511,86511,Zimbabwe,ZWE,2022-03-29,9039729.0,5053114.0,3510256.0,105369.0,...,59.90,33.48,23.26,6874.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,2022,Mar,29

## Deleting Non neccesory columns

In [37]:
del df['Unnamed: 0']
del df['Unnamed: 0.1']
del df['Unnamed: 0.1.1']
df

,country,iso_code,date,total_vaccinations,people_vaccinated,people_fully_vaccinated,daily_vaccinations_raw,daily_vaccinations,total_vaccinations_per_hundred,people_vaccinated_per_hundred,people_fully_vaccinated_per_hundred,daily_vaccinations_per_million,vaccines,source_name,source_website,year,month,day
0,Afghanistan,AFG,2021-02-22,0.0,0.0,NaN,NaN,NaN,0.00,0.00,NaN,NaN,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,2021,Feb,22
1,Afghanistan,AFG,2021-02-23,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,2021,Feb,23
2,Afghanistan,AFG,2021-02-24,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,2021,Feb,24
3,Afghanistan,AFG,2021-02-25,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,2021,Feb,25
4,Afghanistan,AFG,2021-02-26,NaN,NaN,NaN,NaN,1367.0,NaN,NaN,NaN,34.0,"Johnson&Johnson, Oxford/AstraZeneca, Pfizer/Bi...",World Health Organization,https://covid19.who.int/,2021,Feb,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86507,Zimbabwe,ZWE,2022-03-25,8691642.0,4814582.0,3473523.0,139213.0,69579.0,57.59,31.90,23.02,4610.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,2022,Mar,25
86508,Zimbabwe,ZWE,2022-03-26,8791728.0,4886242.0,3487962.0,100086.0,83429.0,58.25,32.38,23.11,5528.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,2022,Mar,26
86509,Zimbabwe,ZWE,2022-03-27,8845039.0,4918147.0,3493763.0,53311.0,90629.0,58.61,32.59,23.15,6005.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,2022,Mar,27
86510,Zimbabwe,ZWE,2022-03-28,8934360.0,4975433.0,3501493.0,89321.0,100614.0,59.20,32.97,23.20,6667.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,2022,Mar,28
86511,Zimbabwe,ZWE,2022-03-29,9039729.0,5053114.0,3510256.0,105369.0,103751.0,59.90,33.48,23.26,6874.0,"Oxford/AstraZeneca, Sinopharm/Beijing, Sinovac...",Ministry of Health,https://www.arcgis.com/home/webmap/viewer.html...,2022,Mar,29

## how many people total vaccinated in india may 21

In [38]:
df_pr = df[(df['country'] == 'India')]
print(df_pr[df_pr['month'] == 'May']['total_vaccinations'].sum())
##print(df_pr[df_pr['month'] == 'Jan']['total_vaccinations'].sum())

5432545301.0

## how many people vaccinated in albania on 22-1-12

In [39]:
df_pr = df[df['country'] == 'Albania']
print(df_pr[df_pr['date'] == 22-1-12]['total_vaccinations'].sum())

0.0

In [40]:
print(df_pr[df_pr['date'] == 22-1-12]['total_vaccinations'].sum())

0.0

## Monthly number of total vaccination from jN TO DEC 2021

In [41]:
df_pr = df[(df['country'] == 'Albania')]
print(df_pr[df_pr['month'] == 'Jan']['total_vaccinations'].sum())
print(df_pr[df_pr['month'] == 'Feb']['total_vaccinations'].sum())
print(df_pr[df_pr['month'] == 'Mar']['total_vaccinations'].sum())
print(df_pr[df_pr['month'] == 'Apr']['total_vaccinations'].sum())
print(df_pr[df_pr['month'] == 'May']['total_vaccinations'].sum())
print(df_pr[df_pr['month'] == 'Jun']['total_vaccinations'].sum())
print(df_pr[df_pr['month'] == 'Jul']['total_vaccinations'].sum())
print(df_pr[df_pr['month'] == 'Aug']['total_vaccinations'].sum())
print(df_pr[df_pr['month'] == 'Sep']['total_vaccinations'].sum())
print(df_pr[df_pr['month'] == 'Oct']['total_vaccinations'].sum())
print(df_pr[df_pr['month'] == 'Nov']['total_vaccinations'].sum())
print(df_pr[df_pr['month'] == 'Dec']['total_vaccinations'].sum())

14479878.0
23971044.0
17173564.0
8374307.0
15597870.0
18904093.0
25369435.0
29463514.0
39078585.0
40171088.0
32124967.0
30832120.0

## No of total vaccination in india in 2020, 2021, 2022?
## compare No. of total vaccination in 2020 in USA?

In [42]:
##No of total vaccination in india in 2020, 2021, 2022?
print('No of total vaccination in india in 2020, 2021, 2022?') 
print(df[df['country'] == 'India']['total_vaccinations'].sum())

## compare No. of total vaccination in 2020 in USA?
print('No of total vaccination in india in 2020, ?') 
df_pr = df[(df['year'] == 2020)]
print(df_pr[df_pr['country'] == 'India']['total_vaccinations'].sum())

print('No of total vaccination in india in 2021?') 
df_pr = df[(df['year'] == 2021)]
print(df_pr[df_pr['country'] == 'India']['total_vaccinations'].sum())

print('No of total vaccination in india in 2022?') 
df_pr = df[(df['year'] == 2022)]
print(df_pr[df_pr['country'] == 'India']['total_vaccinations'].sum())

No of total vaccination in india in 2020, 2021, 2022?
323440305798.0
No of total vaccination in india in 2020, ?
0.0
No of total vaccination in india in 2021?
174118546779.0
No of total vaccination in india in 2022?
149321759019.0

## total no of vaccination in year 2020 in india and USA

In [21]:
print('total no of vaccination in year 2020 in india and USA')
print ('india')
df_pr = df[(df['year'] == 2020)]
print(df_pr[df_pr['country'] == 'India']['total_vaccinations'].sum())
print('USA')
df_pr = df[(df['year'] == 2020)]
print(df_pr[df_pr['country'] == 'United States']['total_vaccinations'].sum())

total no of vaccination in year 2020 in india and USA
india
0.0
USA
41094416.0

## total no of vaccination in year 2020 in india and China

In [43]:
print('total no of vaccination in year 2020 in india and China')
print ('india')
df_pr = df[(df['year'] == 2021)]
print(df_pr[df_pr['country'] == 'India']['total_vaccinations'].sum())
print('China')
df_pr = df[(df['year'] == 2021)]
print(df_pr[df_pr['country'] == 'China']['total_vaccinations'].sum())

total no of vaccination in year 2020 in india and China
india
174118546779.0
China
440076944700.0

## Total no of people vaccinated in year 2021 in india

In [40]:
india_2021 = df_pr = df[(df['country'] == 'India') & (df['year'] == 2021)] 

total_vaccinations_jan_2021 = df_pr[df_pr['month'] == 'Jan']['total_vaccinations'].sum()
print("Total number of people vaccinated in India in jan 2021:", total_vaccinations_jan_2021)

total_vaccinations_feb_2021 = df_pr[df_pr['month'] == 'Feb']['total_vaccinations'].sum()
print("Total number of people vaccinated in India in feb 2021:", total_vaccinations_feb_2021)

total_vaccinations_mar_2021 = df_pr[df_pr['month'] == 'Mar']['total_vaccinations'].sum()
print("Total number of people vaccinated in India in mar 2021:", total_vaccinations_mar_2021)

total_vaccinations_apr_2021 = df_pr[df_pr['month'] == 'Apr']['total_vaccinations'].sum()
print("Total number of people vaccinated in India in apr 2021:", total_vaccinations_apr_2021)

total_vaccinations_may_2021 = df_pr[df_pr['month'] == 'May']['total_vaccinations'].sum()
print("Total number of people vaccinated in India in may 2021:", total_vaccinations_may_2021)

total_vaccinations_jun_2021 = df_pr[df_pr['month'] == 'Jun']['total_vaccinations'].sum()
print("Total number of people vaccinated in India in jun 2021:", total_vaccinations_jun_2021)

total_vaccinations_jul_2021 = df_pr[df_pr['month'] == 'Jul']['total_vaccinations'].sum()
print("Total number of people vaccinated in India in jul 2021:", total_vaccinations_jul_2021)

total_vaccinations_aug_2021 = df_pr[df_pr['month'] == 'Aug']['total_vaccinations'].sum()
print("Total number of people vaccinated in India in aug 2021:", total_vaccinations_aug_2021)

total_vaccinations_sep_2021 = df_pr[df_pr['month'] == 'Sep']['total_vaccinations'].sum()
print("Total number of people vaccinated in India in sep 2021:", total_vaccinations_sep_2021)

total_vaccinations_oct_2021 = df_pr[df_pr['month'] == 'Oct']['total_vaccinations'].sum()
print("Total number of people vaccinated in India in oct 2021:", total_vaccinations_oct_2021)

total_vaccinations_nov_2021 = df_pr[df_pr['month'] == 'Nov']['total_vaccinations'].sum()
print("Total number of people vaccinated in India in nov 2021:", total_vaccinations_nov_2021)

total_vaccinations_dec_2021 = df_pr[df_pr['month'] == 'Dec']['total_vaccinations'].sum()
print("Total number of people vaccinated in India in dec 2021:", total_vaccinations_dec_2021)

Total number of people vaccinated in India in jan 2021: 28323206.0
Total number of people vaccinated in India in feb 2021: 237762147.0
Total number of people vaccinated in India in mar 2021: 1166006861.0
Total number of people vaccinated in India in apr 2021: 3038130111.0
Total number of people vaccinated in India in may 2021: 5432545301.0
Total number of people vaccinated in India in jun 2021: 7930055407.0
Total number of people vaccinated in India in jul 2021: 11129697938.0
Total number of people vaccinated in India in aug 2021: 15593466811.0
Total number of people vaccinated in India in sep 2021: 23162890858.0
Total number of people vaccinated in India in oct 2021: 30299754484.0
Total number of people vaccinated in India in nov 2021: 34164994865.0
Total number of people vaccinated in India in dec 2021: 41934918790.0

## Total number of people vaccinated in India in May 2021

In [32]:
india_2021 = df[(df['country'] == 'India') & (df['year'] == 2021) & (df['month'] == 'May')]
total_vaccinations_may_2021 = india_may_2021['total_vaccinations'].sum()
print("Total number of people vaccinated in India in May 2021:", total_vaccinations_may_2021)

Total number of people vaccinated in India in May 2021: 5432545301.0

## Month with the most number of total vaccinations in India in 2021

In [70]:
india_vaccinations_2021 = df[(df['country'] == 'India') & (df['year'] == 2021)]

# Grouping data by month and calculating total vaccinations for each month in 2021
total_vaccinations_by_month_2021 = india_vaccinations_2021.groupby('month')['total_vaccinations'].sum().reset_index()

# Finding the month with the most vaccinations in 2021
most_vaccinated_month_2021 = total_vaccinations_by_month_2021.loc[total_vaccinations_by_month_2021['total_vaccinations'].idxmax()]

print("Month with the most number of total vaccinations in India in 2021:", most_vaccinated_month_2021['month'])

Month with the most number of total vaccinations in India in 2021: Dec

In [51]:
df.to_csv('processed_country_wise_latest.csv')
P2.to_csv('processed_covid.csv')